version: '3.8'
services:
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: teamb
      POSTGRES_PASSWORD: password
      POSTGRES_DB: teamb

  backend:
    build: 
      context: ./back
      dockerfile: Dockerfile  # 必要に応じてDockerfileの名前を指定
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://teamb:password@db/teamb
      OPENAI_API_KEY: ${OPENAI_API_KEY}  # .envから読み込まれます    
    volumes:
      - ./back:/app  # ホストマシンのbackディレクトリをコンテナの/appディレクトリにマウント
      - ./.env:/app/.env   # .envファイルをコンテナ内の/appディレクトリにマウント
      # - ./Log:/logs   # ログをホストマシンのディレクトリに保存する

  frontend:
    build: ./front
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
    - ./front:/app  # ローカルのfrontディレクトリをコンテナの/appディレクトリにマウント
    - /app/node_modules  # コンテナのnode_modulesを保持
    -  /app/.next # Next.jsアプリケーションのビルドファイルがホストマシンとコンテナー間で共有
    environment:
      - NODE_ENV=development # 開発モードで Next.js が起動
      - WATCHPACK_POLLING=true # ポーリングを有効にしてファイルシステムのイベントを正確に捕捉

  # stripe-cli:
  #   image: stripe/stripe-cli:latest
  #   stdin_open: true
  #   tty: true
  #   environment:
  #     STRIPE_API_KEY: your_stripe_api_key_here
  #   ports:
  #     - "3001:3001"
  #   volumes:
  #     - ./stripe_data:/data

volumes:
  postgres_data:


# version: '3.8'
# services:
#   pgadmin:
#     image: dpage/pgadmin4
#     restart: always
#     ports:
#       - "5050:80"
#     environment:
#       PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
#       PGADMIN_DEFAULT_PASSWORD: "root"
#     depends_on:
#       - db
      
#   db:
#     image: postgres
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     environment:
#       POSTGRES_USER: teamb
#       POSTGRES_PASSWORD: password
#       POSTGRES_DB: teamb

#   backend:
#     build: ./back
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db
#     environment:
#       DATABASE_URL: postgresql://teamb:password@db/teamb
#     volumes:
#       - ./back:/app  # ホストマシンのbackディレクトリをコンテナの/appディレクトリにマウント

#   frontend:
#     build: ./front
#     ports:
#       - "3000:3000"
#     depends_on:
#       - backend

# volumes:
#   postgres_data:
